#!/bin/bash
# -----------------------------------------------------------------------
# Copyright C.Williams 2018 All rights reserved
# -----------------------------------------------------------------------
#
# Synopsis:
#   Creates a date based notebook using vim as an editor as a collection of datestamp named files
#
# -----------------------------------------------------------------------
# default settings
NoteBase=~/NoteBooks
NoteBook=diary

# override from config file if it exists
ConfigFile="${HOME}/.vimdiary"
if [ -f ${ConfigFile} ]; then
    source ${ConfigFile}
fi

# process command line
script=`basename "$0"`
while [[ $# -gt 0 ]]
do
key="$1"
case $key in
    -h|--help)
        echo Synopsis:
        echo "   Creates a date based notebook using vim as an editor."
        echo "   Notes are stored a collection of date stamped files."
        echo ""
        echo Usage:
        echo "   ${script} [OPTIONS] [notebook]"
        echo ""
        echo Options:
        echo "   notebook       : the name of the notebook (default=${NoteBook})"
        echo "                    n.b each notebook will be stored in its"
        echo "                     own subdirectory."
        echo "   -e|--env       : display config info to screen and exit"
        echo "   -l|--list      : list the notebooks that exist"
        echo "   -y|--yesterday : open yesterdays entry"
        echo ""
        echo Configuration File:
        echo "    If the file ${ConfigFile} exists it will be read for the variables"
        echo "        NoteBook=<default_notebook>"
        echo "        NoteBase=<Path to Notebook File Storage"
        exit 0;
        ;;
     -e|--env)
        echo "Notebook base: ${NoteBase}"
        exit 0;
        ;;
     -l|--list)
        find ${NoteBase} -mindepth 1 -maxdepth 1 -type d -print | xargs basename -a
        exit 0;
        ;;
     -y|--yesterday)
        date_str="-d 'yesterday 13:00'"
        shift;
        ;;
     -*)
        echo "Unknown option: $1"
        exit 1;
        ;;
     *)
        NoteBook=$1
        shift
        ;;
esac
done

# capitalise first letter of NoteBook name given
notebook=`echo ${NoteBook} | tr "[A-Z]" "[a-z]"`
NoteBookName=`echo ${notebook} | sed -e "s/_/ /g" -e "s/\b\(.\)/\u\1/g"`
dir=${NoteBase}/${notebook}

mkdir -p ${dir}
date_fname=`eval date ${date_str} +\"%Y_%b_%d\"`;
filename=${dir}/$date_fname
if [ ! -f ${filename} ]; then
echo Creating ${NoteBookName} entry ${filename}
echo "--------------------------------------------------------------------------------" > ${filename}
echo -n "${NoteBookName}: " >> ${filename}
(eval date ${date_str} +\"%a %d %b %Y\") >> ${filename}
echo "--------------------------------------------------------------------------------" >> ${filename}
else
chmod +w ${filename}
echo "" >> ${filename}
fi
date +"(%R)" >> ${filename}
echo -n "     " >> ${filename}
cd ${dir} && vim "+normal G$" +startinsert ${filename}
chmod -w ${filename}
